In [2]:
#import the library Pandas
import pandas as pd

In [3]:
#Put the People Charm case.csv dataset on Root Directory
#Read the dataset 
data = pd.read_csv('People Charm case.csv')

In [4]:
#Showing the 5 Data of given dataset
data

,satisfactoryLevel,lastEvaluation,numberOfProjects,avgMonthlyHours,timeSpent.company,workAccident,left,promotionInLast5years,dept,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.37,0.52,2,159,3,0,1,0,sales,low
4,0.41,0.50,2,153,3,0,1,0,sales,low
5,0.10,0.77,6,247,4,0,1,0,sales,low
6,0.92,0.85,5,259,5,0,1,0,sales,low
7,0.42,0.53,2,142,3,0,1,0,sales,low
8,0.45,0.54,2,135,3,0,1,0,sales,low
9,0.11,0.81,6,305,4,0,1,0,sales,low
10,0.36,0.56,2,137,3,0,1,0,sales,low
11,0.38,0.54,2,143,3,0,1,0,sales,low
12,0.45,0.47,2,160,3,0,1,0,sales,low
13,0.78,0.99,4,255,6,0,1,0,sales,low
14,0.76,0.89,5,262,5,0,1,0,sales,low
15,0.11,0.83,6,282,4,0,1,0,sales,low
16,0.09,0.95,6,304,4,0,1,0,sales,low
17,0.46,0.57,2,139,3,0,1,0,sales,low
18,0.40,0.53,2,158,3,0,1,0,sales,low
19,0.89,0.92,5,242,5,0,1,0,sales,low
20,0.82,0.87,4,239,5,0,1,0,sales,low
21,0.40,0.49,2,135,3,0,1,0,sales,low
22,0.38,0.50,2,132,3,0,1,0,accounting,low
23,0.09,0.62,6,294,4,0,1,0,accounting,low
24,0.45,0.57,2,134,3,0,1,0,hr,low
25,0.40,0.51,2,145,3,0,1,0,hr,low
26,0.84,0.87,4,246,6,0,1,0,hr,low
27,0.38,0.46,2,137,3,0,1,0,technical,low
28,0.45,0.50,2,126,3,0,1,0,technical,low
29,0.11,0.89,6,306,4,0,1,0,technical,low
...,...,...,...,...,...,...,...,...,...,...
14969,0.22,0.91,6,222,8,0,0,0,technical,low
14970,0.43,0.48,2,135,3,0,1,0,sales,medium
14971,0.42,0.48,2,143,3,0,1,0,sales,low
14972,0.82,0.97,4,243,3,1,0,0,technical,low
14973,0.73,0.60,3,145,6,1,0,0,technical,medium
14974,0.10,0.55,2,247,4,0,1,0,sales,medium
14975,0.57,1.00,3,241,4,0,0,0,technical,low
14976,0.97,0.66,4,218,3,0,0,0,sales,high
14977,0.21,0.62,4,247,3,1,0,0,product_mng,low
14978,0.64,0.50,3,238,4,0,0,0,technical,low
14979,0.37,0.46,2,149,3,0,1,0,marketing,high
14980,0.88,0.75,4,201,2,0,0,0,sales,medium
14981,0.97,0.55,4,166,3,1,0,0,accounting,high
14982,0.88,0.80,3,133,3,0,0,0,product_mng,medium
14983,0.77,0.67,3,186,2,0,0,0,technical,low
14984,0.62,0.71,4,268,3,0,0,0,technical,low
14985,0.95,0.84,3,270,3,1,0,1,sales,medium
14986,0.76,1.00,4,220,6,0,1,0,RandD,medium
14987,0.37,0.45,2,126,3,0,1,0,support,medium
14988,0.43,0.57,2,157,3,0,1,0,sales,low
14989,0.69,0.70,3,212,2,0,0,0,product_mng,medium
14990,0.73,0.52,3,274,2,0,0,0,technical,high
14991,0.85,0.53,3,250,3,0,0,0,IT,medium
14992,0.30,0.88,5,245,4,0,0,0,hr,low
14993,0.61,0.89,3,242,10,0,0,0,sales,high
14994,0.11,0.85,7,275,4,0,1,0,support,medium
14995,0.99,0.83,4,274,2,0,0,0,sales,low
14996,0.72,0.72,4,175,4,0,0,0,technical,low
14997,0.24,0.91,5,177,5,0,0,0,sales,low
14998,0.77,0.83,6,271,3,0,0,0,support,low

In [5]:
# To perform numerical operations
import numpy as np
# To Visualize data
import seaborn as sns

In [6]:
# To Partition the data
from sklearn.model_selection import train_test_split
# Importing library for logistic regression
from sklearn.linear_model import LogisticRegression

In [7]:
# Importing performance metrics - accuracy score & confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix

In [9]:
#============================================
#   Logistic Regression Model
#============================================
new_data = pd.get_dummies(data,drop_first = True)
columns_list = list(new_data.columns)
print(columns_list)

# Separating the input names from data
features=list(set(columns_list)-set(['left']))
print(features)

# Storing the output values in y
y=new_data['left'].values
print(y)

# Storing the values from input features
x = new_data[features].values
print(x)
# Spiliting the data into train and test
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.25,random_state=2)

# Make an instance of the Model
logistic = LogisticRegression()

# Fitting the Values for x and y
logistic.fit(train_x,train_y)

# Pridiction from test data
prediction = logistic.predict(test_x)

# Confusion matrix
confusion_matrix = confusion_matrix(test_y,prediction)
print(confusion_matrix)

# Calculating the accuracy
accuracy_score = accuracy_score(test_y,prediction)
print(accuracy_score)

# Printing the misclassified values from Prediction
print('Misclassified samples: %d' % (test_y != prediction).sum())

['satisfactoryLevel', 'lastEvaluation', 'numberOfProjects', 'avgMonthlyHours', 'timeSpent.company', 'workAccident', 'left', 'promotionInLast5years', 'dept_RandD', 'dept_accounting', 'dept_hr', 'dept_management', 'dept_marketing', 'dept_product_mng', 'dept_sales', 'dept_support', 'dept_technical', 'salary_low', 'salary_medium']
['lastEvaluation', 'salary_low', 'dept_hr', 'satisfactoryLevel', 'promotionInLast5years', 'avgMonthlyHours', 'dept_management', 'dept_RandD', 'dept_product_mng', 'workAccident', 'dept_technical', 'dept_accounting', 'salary_medium', 'dept_marketing', 'numberOfProjects', 'timeSpent.company', 'dept_support', 'dept_sales']
[1 1 1 ... 0 0 0]
[[0.53 1.   0.   ... 3.   0.   1.  ]
 [0.86 0.   0.   ... 6.   0.   1.  ]
 [0.88 0.   0.   ... 4.   0.   1.  ]
 ...
 [0.72 1.   0.   ... 4.   0.   0.  ]
 [0.91 1.   0.   ... 5.   0.   1.  ]
 [0.83 1.   0.   ... 3.   1.   0.  ]]
[[2687  181]
 [ 564  318]]
0.8013333333333333
Misclassified samples: 745

C:\Users\my pc\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [10]:
# The accuracy score for the predicted model
print(accuracy_score)

0.8013333333333333

In [11]:
# Printing the misclassified values from Prediction
print('Misclassified samples: %d' % (test_y != prediction).sum())

Misclassified samples: 745